name: CI

on:
  push:
    paths:
      - 'Pages/**'
      - 'Properties/**'
      - 'wwwroot/**'
      - '*.csproj'
      - '*.json'
      - '**/*.cs'
      - '.github/workflows/ci.yml'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

env:
  ARTIFACT_NAME: account-system

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --nologo --configuration Release --no-restore --no-self-contained

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: bin/Release/net7.0/*
